version: '3.3'

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend-net

  web:
    build: .
    # tty: true
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_ENV=prod
      - SECRET=${SECRET}
      - CORS_WHITELIST_DOMAIN=${CORS_WHITELIST_DOMAIN}
    command: gunicorn --workers=4 \
    --log-file=/var/log/kamusy/gunicorn.log \
    --bind=127.0.0.1:8000 --bind=[::1]:8000 \
    kamusy.wsgi:application
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - backend-net

networks:
  backend-net:
    external: true
