version: '3.3'

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend-net
  redis:
    image: redis:7-alpine
    depends_on:
      - db
    networks:
      - backend-net
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    # tty: true
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_ENV=prod
      - SECRET=${SECRET}
      - CORS_WHITELIST_DOMAIN=${CORS_WHITELIST_DOMAIN}
    command: gunicorn kamusy.wsgi:application --workers=8 --bind=0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - backend-net

networks:
  backend-net:
    external: true
