# Generated by Django 3.2.7 on 2021-10-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0003_auto_20211001_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
