# Generated by Django 3.2.7 on 2021-10-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True, help_text='The description of the term being explained', null=True, verbose_name='The Explanation'),
        ),
    ]
