# Generated by Django 3.2.7 on 2021-10-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_word_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
    ]
