# Generated by Django 3.2.3 on 2021-10-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_alter_word_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('name',)},
        ),
    ]
