# Generated by Django 3.2.7 on 2021-10-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translation', '0001_initial'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='word_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_destination', to='word.word'),
        ),
        migrations.AddField(
            model_name='translation',
            name='word_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_source', to='word.word'),
        ),
    ]
